-- SISTEMA DE TORNEIO SEMANAL AUTOMATICO

-- 1. ADICIONAR COLUNAS À TABELA tournaments
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS is_weekly BOOLEAN DEFAULT FALSE;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS total_collected DECIMAL DEFAULT 0;
ALTER TABLE tournaments ADD COLUMN IF NOT EXISTS prize_paid BOOLEAN DEFAULT FALSE;

-- 2. CRIAR INDICES
CREATE INDEX IF NOT EXISTS idx_tournaments_is_weekly ON tournaments(is{