/**
 * discord-chat-sync
 *
 * Serverless replacement for the Java gateway bot (Discord -> DuelVerse direction).
 * Triggered every minute by pg_cron (job "discord-chat-sync", see migration
 * 20261002090000_discord_chat_sync.sql). For every Discord channel bridged by the
 * app (system_settings.discord_bot_status.servers[].channelId — the same servers
 * chat_to_discord posts to), it reads new messages through the Discord REST API
 * and inserts them into public.global_chat_messages using the exact same row
 * format as discord-bridge's discord_to_chat path (shared module).
 *
 * Auth: header x-cron-secret must match the vault secret "discord_chat_sync_secret"
 * (generated by the migration, read through a service_role-only RPC).
 * If the secret is missing the function answers 503 and does nothing.
 */
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { insertDiscordChatMessage } from "../_shared/discord-chat.ts";
import { checkCronAuth, type CursorStore, resolveBridgeChannelIds, syncAllChannels } from "./sync.ts";

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });

serve(async (req) => {
  if (req.method !== "POST") return json({ error: "Method not allowed" }, 405);

  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!supabaseUrl || !serviceKey) return json({ error: "Not configured" }, 503);
  const supabase = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false } });

  // 1. Authenticate the cron call (fail closed).
  let expectedSecret: string | null = null;
  try {
    const { data, error } = await supabase.rpc("get_discord_chat_sync_secret");
    if (error) console.error("[discord-chat-sync] secret lookup failed:", error.message);
    else if (typeof data === "string") expectedSecret = data;
  } catch (err) {
    console.error("[discord-chat-sync] secret lookup threw:", err);
  }
  const auth = checkCronAuth(expectedSecret, req.headers.get("x-cron-secret"));
  if (auth === "not_configured") {
    console.warn("[discord-chat-sync] cron secret not configured; refusing to run");
    return json({ error: "Sync secret not configured" }, 503);
  }
  if (auth === "unauthorized") return json({ error: "Unauthorized" }, 401);

  const botToken = Deno.env.get("DISCORD_BOT_TOKEN");
  if (!botToken) return json({ error: "DISCORD_BOT_TOKEN not configured" }, 503);

  try {
    // 2. Same channel source as chat_to_discord.
    const { data: cfg, error: cfgError } = await supabase
      .from("system_settings")
      .select("value")
      .eq("key", "discord_bot_status")
      .maybeSingle();
    if (cfgError) return json({ error: cfgError.message }, 500);
    const channelIds = resolveBridgeChannelIds(cfg?.value);
    if (channelIds.length === 0) return json({ ok: true, channels: 0, skipped: "no_bridged_channels" });

    // 3. Cursor store: service_role-only table.
    const cursors: CursorStore = {
      async get(channelId) {
        const { data, error } = await supabase
          .from("discord_chat_sync_state")
          .select("last_message_id")
          .eq("channel_id", channelId)
          .maybeSingle();
        if (error) throw new Error(`cursor read failed: ${error.message}`);
        return data?.last_message_id ?? null;
      },
      async set(channelId, lastMessageId) {
        const { error } = await supabase
          .from("discord_chat_sync_state")
          .upsert(
            { channel_id: channelId, last_message_id: lastMessageId, updated_at: new Date().toISOString() },
            { onConflict: "channel_id" },
          );
        if (error) throw new Error(`cursor write failed: ${error.message}`);
      },
    };

    const results = await syncAllChannels(
      {
        botToken,
        fetchImpl: fetch,
        sleep: (ms) => new Promise((r) => setTimeout(r, ms)),
        now: () => Date.now(),
        cursors,
        insert: (input) => insertDiscordChatMessage(supabase, input),
        log: (m) => console.log(m),
      },
      channelIds,
    );

    for (const r of results) {
      const line = `[discord-chat-sync] channel=${r.channelId} status=${r.status} fetched=${r.fetched} inserted=${r.inserted} dup=${r.duplicates} skipped=${JSON.stringify(r.skipped)}`;
      if (r.status === "error") console.error(`${line} error=${r.error}`);
      else console.log(line);
    }
    const anyError = results.some((r) => r.status === "error");
    return json({ ok: !anyError, channels: results.length, results }, anyError ? 502 : 200);
  } catch (err) {
    console.error("[discord-chat-sync] critical error:", err);
    return json({ error: err instanceof Error ? err.message : String(err) }, 500);
  }
});
