-- Adicionar a coluna duelcoins_balance à tabela profiles
ALTER TABLE public.profiles
ADD COLUMN duelcoins_balance INTEGER NOT NULL DEFAULT 0;

-- Criar a tabela duelcoins_transactions
CREATE TABLE public.duelcoins_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID NOT NULL REFERENCES public.profiles(user_id),
  receiver_id UUID NOT NULL REFERENCES public.profiles(user_id),
  amount INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Adicionar políticas de segurança para a tabela duelcoins_transactions
ALTER TABLE public.duelcoins_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Os usuários podem ver suas próprias transações"
ON public.duelcoins_transactions
FOR SELECT
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Os usuários podem registrar novas transações"
ON public.duelcoins_transactions
FOR INSERT
WITH CHECK (auth.uid() = sender_id);
