-- Refresh official Konami GENESYS point rows in genesis_card_costs.
-- Source: https://www.yugioh-card.com/en/genesys/

INSERT INTO public.genesis_card_costs (card_id, card_name, points)
VALUES
  ('official:"a case for k9"', '"A Case for K9"', 20),
  ('official:abyss dweller', 'Abyss Dweller', 100),
  ('official:adamancipator risen - dragite', 'Adamancipator Risen - Dragite', 20),
  ('official:agido the ancient sentinel', 'Agido the Ancient Sentinel', 50),
  ('official:albion the branded dragon', 'Albion the Branded Dragon', 5),
  ('official:albion the sanctifire dragon', 'Albion the Sanctifire Dragon', 33),
  ('official:allure of darkness', 'Allure of Darkness', 5),
  ('official:ame no habakiri no mitsurugi', 'Ame no Habakiri no Mitsurugi', 100),
  ('official:amorphactor pain, the imagination dracoverlord', 'Amorphactor Pain, the Imagination Dracoverlord', 100),
  ('official:ancient gear advance', 'Ancient Gear Advance', 33),
  ('official:ancient gear statue', 'Ancient Gear Statue', 33),
  ('official:and the band played on', 'And the Band Played On', 100),
  ('official:angel o7', 'Angel O7', 100),
  ('official:anti-spell fragrance', 'Anti-Spell Fragrance', 100),
  ('official:appointer of the red lotus', 'Appointer of the Red Lotus', 50),
  ('official:arcana force xxi - the world', 'Arcana Force XXI - The World', 100),
  ('official:archlord kristya', 'Archlord Kristya', 100),
  ('official:archnemeses eschatos', 'Archnemeses Eschatos', 100),
  ('official:archnemeses protos', 'Archnemeses Protos', 100),
  ('official:artifact scythe', 'Artifact Scythe', 100),
  ('official:artmage non-finito', 'Artmage Non-Finito', 15),
  ('official:artmage vandalism -assault-', 'Artmage Vandalism -Assault-', 3),
  ('official:artmage varnish -alteration-', 'Artmage Varnish -Alteration-', 3),
  ('official:ash blossom & joyous spring', 'Ash Blossom & Joyous Spring', 20),
  ('official:assault synchron', 'Assault Synchron', 1),
  ('official:astral kuriboh', 'Astral Kuriboh', 3),
  ('official:atlantean dragoons', 'Atlantean Dragoons', 40),
  ('official:azamina ilia silvia', 'Azamina Ilia Silvia', 20),
  ('official:azamina mu rcielago', 'Azamina Mu Rcielago', 33),
  ('official:bahamut shark', 'Bahamut Shark', 81),
  ('official:banquet of millions', 'Banquet of Millions', 51),
  ('official:baronne de fleur', 'Baronne de Fleur', 80),
  ('official:barrier of the voiceless voice', 'Barrier of the Voiceless Voice', 15),
  ('official:barrier statue of the abyss', 'Barrier Statue of the Abyss', 70),
  ('official:barrier statue of the drought', 'Barrier Statue of the Drought', 70),
  ('official:barrier statue of the heavens', 'Barrier Statue of the Heavens', 70),
  ('official:barrier statue of the inferno', 'Barrier Statue of the Inferno', 70),
  ('official:barrier statue of the stormwinds', 'Barrier Statue of the Stormwinds', 70),
  ('official:barrier statue of the torrent', 'Barrier Statue of the Torrent', 70),
  ('official:beatrice, lady of the eternal', 'Beatrice, Lady of the Eternal', 100),
  ('official:beelze of the diabolic dragons', 'Beelze of the Diabolic Dragons', 100),
  ('official:big welcome labrynth', 'Big Welcome Labrynth', 20),
  ('official:black garden', 'Black Garden', 51),
  ('official:black-winged assault dragon', 'Black-Winged Assault Dragon', 1),
  ('official:blackwing - boreastorm the wicked wind', 'Blackwing - Boreastorm the Wicked Wind', 20),
  ('official:blackwing - zephyros the elite', 'Blackwing - Zephyros the Elite', 13),
  ('official:blaster, dragon ruler of infernos', 'Blaster, Dragon Ruler of Infernos', 5),
  ('official:blaze fenix, the burning bombardment bird', 'Blaze Fenix, the Burning Bombardment Bird', 70),
  ('official:blazing cartesia, the virtuous', 'Blazing Cartesia, the Virtuous', 3),
  ('official:block dragon', 'Block Dragon', 33),
  ('official:bonfire', 'Bonfire', 33),
  ('official:book of eclipse', 'Book of Eclipse', 3),
  ('official:book of moon', 'Book of Moon', 4),
  ('official:brain research lab', 'Brain Research Lab', 100),
  ('official:bramble rose dragon', 'Bramble Rose Dragon', 1),
  ('official:branded expulsion', 'Branded Expulsion', 33),
  ('official:branded fusion', 'Branded Fusion', 40),
  ('official:branded lost', 'Branded Lost', 66),
  ('official:brilliant fusion', 'Brilliant Fusion', 33),
  ('official:broww, huntsman of dark world', 'Broww, Huntsman of Dark World', 3),
  ('official:butterfly dagger - elma', 'Butterfly Dagger - Elma', 1),
  ('official:bystial baldrake', 'Bystial Baldrake', 30),
  ('official:bystial dis pater', 'Bystial Dis Pater', 10),
  ('official:bystial druiswurm', 'Bystial Druiswurm', 30),
  ('official:bystial magnamhut', 'Bystial Magnamhut', 33),
  ('official:bystial saronir', 'Bystial Saronir', 20),
  ('official:called by the grave', 'Called by the Grave', 20),
  ('official:card destruction', 'Card Destruction', 40),
  ('official:card of demise', 'Card of Demise', 40),
  ('official:card of safe return', 'Card of Safe Return', 33),
  ('official:catapult turtle', 'Catapult Turtle', 100),
  ('official:celestial observatory', 'Celestial Observatory', 5),
  ('official:centur-ion auxila', 'Centur-Ion Auxila', 33),
  ('official:centur-ion primera', 'Centur-Ion Primera', 2),
  ('official:centur-ion trudea', 'Centur-Ion Trudea', 1),
  ('official:chain strike', 'Chain Strike', 50),
  ('official:change of heart', 'Change of Heart', 6),
  ('official:chaofeng, phantom of the yang zing', 'Chaofeng, Phantom of the Yang Zing', 13),
  ('official:chaos angel', 'Chaos Angel', 20),
  ('official:chaos ruler, the chaotic magical dragon', 'Chaos Ruler, the Chaotic Magical Dragon', 50),
  ('official:chaos space', 'Chaos Space', 40),
  ('official:charge of the light brigade', 'Charge of the Light Brigade', 25),
  ('official:chicken game', 'Chicken Game', 7),
  ('official:cold wave', 'Cold Wave', 100),
  ('official:confiscation', 'Confiscation', 100),
  ('official:contact "c"', 'Contact "C"', 100),
  ('official:cornfield coatl', 'Cornfield Coatl', 33),
  ('official:cosmic blazar dragon', 'Cosmic Blazar Dragon', 21),
  ('official:cosmic cyclone', 'Cosmic Cyclone', 1),
  ('official:creature swap', 'Creature Swap', 1),
  ('official:crimson dragon', 'Crimson Dragon', 80),
  ('official:crossout designator', 'Crossout Designator', 20),
  ('official:crystron inclusion', 'Crystron Inclusion', 25),
  ('official:crystron sulfador', 'Crystron Sulfador', 5),
  ('official:cxyz gimmick puppet fanatix machinix', 'CXyz Gimmick Puppet Fanatix Machinix', 100),
  ('official:cyber angel benten', 'Cyber Angel Benten', 40),
  ('official:cyber dragon infinity', 'Cyber Dragon Infinity', 20),
  ('official:cyber jar', 'Cyber Jar', 33),
  ('official:cyber-stein', 'Cyber-Stein', 27),
  ('official:d.d. crow', 'D.D. Crow', 1),
  ('official:d.d. dynamite', 'D.D. Dynamite', 51),
  ('official:d/d/d duo-dawn king kali yuga', 'D/D/D Duo-Dawn King Kali Yuga', 77),
  ('official:d/d/d wave high king caesar', 'D/D/D Wave High King Caesar', 20),
  ('official:daigusto emeral', 'Daigusto Emeral', 1),
  ('official:danger! bigfoot!', 'Danger! Bigfoot!', 3),
  ('official:danger! chupacabra!', 'Danger! Chupacabra!', 3),
  ('official:danger! dogman!', 'Danger! Dogman!', 3),
  ('official:danger! mothman!', 'Danger! Mothman!', 3),
  ('official:danger! nessie!', 'Danger! Nessie!', 7),
  ('official:danger! ogopogo!', 'Danger! Ogopogo!', 3),
  ('official:danger! thunderbird!', 'Danger! Thunderbird!', 3),
  ('official:danger!? jackalope?', 'Danger!? Jackalope?', 7),
  ('official:danger!? tsuchinoko?', 'Danger!? Tsuchinoko?', 7),
  ('official:dark end evaporation dragon', 'Dark End Evaporation Dragon', 1),
  ('official:dark eradicator warlock', 'Dark Eradicator Warlock', 100),
  ('official:dark hole', 'Dark Hole', 1),
  ('official:dark magician of destruction', 'Dark Magician of Destruction', 15),
  ('official:dark ruler no more', 'Dark Ruler No More', 2),
  ('official:dark world archives', 'Dark World Archives', 5),
  ('official:dark world dealings', 'Dark World Dealings', 5),
  ('official:darklord ixchel', 'Darklord Ixchel', 5),
  ('official:deception of the sinful spoils', 'Deception of the Sinful Spoils', 40),
  ('official:deck lockdown', 'Deck Lockdown', 100),
  ('official:deep sea aria', 'Deep Sea Aria', 33),
  ('official:delinquent duo', 'Delinquent Duo', 100),
  ('official:demise of the land', 'Demise of the Land', 1),
  ('official:denglong, first of the yang zing', 'Denglong, First of the Yang Zing', 20),
  ('official:denko sekka', 'Denko Sekka', 20),
  ('official:destiny hero - destroyer phoenix enforcer', 'Destiny HERO - Destroyer Phoenix Enforcer', 20),
  ('official:destiny hero - plasma', 'Destiny HERO - Plasma', 20),
  ('official:destructive daruma karma cannon', 'Destructive Daruma Karma Cannon', 1),
  ('official:diabell, queen of the white forest', 'Diabell, Queen of the White Forest', 25),
  ('official:diabellstar the black witch', 'Diabellstar the Black Witch', 20),
  ('official:different dimension ground', 'Different Dimension Ground', 10),
  ('official:dimension fusion', 'Dimension Fusion', 40),
  ('official:dimension shifter', 'Dimension Shifter', 10),
  ('official:dimensional barrier', 'Dimensional Barrier', 100),
  ('official:dinomorphia domain', 'Dinomorphia Domain', 1),
  ('official:dinomorphia frenzy', 'Dinomorphia Frenzy', 1),
  ('official:dinomorphia intact', 'Dinomorphia Intact', 1),
  ('official:dinomorphia rexterm', 'Dinomorphia Rexterm', 91),
  ('official:dinowrestler pankratops', 'Dinowrestler Pankratops', 5),
  ('official:divine arsenal aa-zeus - sky thunder', 'Divine Arsenal AA-ZEUS - Sky Thunder', 20),
  ('official:diviner of the herald', 'Diviner of the Herald', 33),
  ('official:djinn releaser of rituals', 'Djinn Releaser of Rituals', 100),
  ('official:dodododo warrior', 'Dodododo Warrior', 70),
  ('official:dogmatika ecclesia, the virtuous', 'Dogmatika Ecclesia, the Virtuous', 3),
  ('official:domain of the true monarchs', 'Domain of the True Monarchs', 50),
  ('official:dominus impulse', 'Dominus Impulse', 20),
  ('official:dominus purge', 'Dominus Purge', 10),
  ('official:dracotail arthalion', 'Dracotail Arthalion', 20),
  ('official:dracotail faimena', 'Dracotail Faimena', 30),
  ('official:dracotail flame', 'Dracotail Flame', 3),
  ('official:dracotail mululu', 'Dracotail Mululu', 7),
  ('official:dragon master magia', 'Dragon Master Magia', 100),
  ('official:dragon''s bind', 'Dragon''s Bind', 100),
  ('official:dragon''s light and darkness', 'Dragon''s Light and Darkness', 3),
  ('official:dragon''s mind', 'Dragon''s Mind', 7),
  ('official:dragonic diagram', 'Dragonic Diagram', 15),
  ('official:dragonmaid sheou', 'Dragonmaid Sheou', 10),
  ('official:dragonmaid tidying', 'Dragonmaid Tidying', 5),
  ('official:droll & lock bird', 'Droll & Lock Bird', 20),
  ('official:drytron alpha thuban', 'Drytron Alpha Thuban', 33),
  ('official:drytron mu beta fafnir', 'Drytron Mu Beta Fafnir', 33),
  ('official:duality', 'Duality', 3),
  ('official:earthbound immortal aslla piscu', 'Earthbound Immortal Aslla piscu', 51),
  ('official:ecclesia and the dark dragon', 'Ecclesia and the Dark Dragon', 3),
  ('official:eclipse wyvern', 'Eclipse Wyvern', 33),
  ('official:effect veiler', 'Effect Veiler', 8),
  ('official:el shaddoll apkallone', 'El Shaddoll Apkallone', 10),
  ('official:el shaddoll winda', 'El Shaddoll Winda', 60),
  ('official:elder entity n''tss', 'Elder Entity N''tss', 7),
  ('official:elder entity norden', 'Elder Entity Norden', 91),
  ('official:elfnote power patron', 'Elfnote Power Patron', 15),
  ('official:elzette, azamina of the white forest', 'Elzette, Azamina of the White Forest', 22),
  ('official:emergency teleport', 'Emergency Teleport', 35),
  ('official:emergency!', 'EMERGENCY!', 33),
  ('official:eva', 'Eva', 1),
  ('official:evenly matched', 'Evenly Matched', 7),
  ('official:evigishki gustkraken', 'Evigishki Gustkraken', 100),
  ('official:evigishki mind augus', 'Evigishki Mind Augus', 1),
  ('official:evilswarm ouroboros', 'Evilswarm Ouroboros', 100),
  ('official:evolzar lars', 'Evolzar Lars', 20),
  ('official:exosister betrayal', 'Exosister Betrayal', 7),
  ('official:exosister mikailis', 'Exosister Mikailis', 10),
  ('official:exosister pax', 'Exosister Pax', 5),
  ('official:expurrely noir', 'Expurrely Noir', 33),
  ('official:ext ryzeal', 'Ext Ryzeal', 25),
  ('official:f.a. dawn dragster', 'F.A. Dawn Dragster', 20),
  ('official:fairy tail - snow', 'Fairy Tail - Snow', 85),
  ('official:fallen of the white dragon', 'Fallen of the White Dragon', 30),
  ('official:fiber jar', 'Fiber Jar', 30),
  ('official:filia regis', 'Filia Regis', 10),
  ('official:final countdown', 'Final Countdown', 100),
  ('official:fire formation - tenki', 'Fire Formation - Tenki', 35),
  ('official:fire king courtier ulcanix', 'Fire King Courtier Ulcanix', 18),
  ('official:fire king high avatar kirin', 'Fire King High Avatar Kirin', 7),
  ('official:fishborg blaster', 'Fishborg Blaster', 33),
  ('official:floowandereeze & robina', 'Floowandereeze & Robina', 33),
  ('official:floowandereeze and the advent of adventure', 'Floowandereeze and the Advent of Adventure', 33),
  ('official:floowandereeze and the magnificent map', 'Floowandereeze and the Magnificent Map', 33),
  ('official:flying "c"', 'Flying "C"', 7),
  ('official:foolish burial', 'Foolish Burial', 33),
  ('official:foolish burial goods', 'Foolish Burial Goods', 7),
  ('official:forbidden chalice', 'Forbidden Chalice', 5),
  ('official:forbidden crown', 'Forbidden Crown', 10),
  ('official:forbidden droplet', 'Forbidden Droplet', 10),
  ('official:forbidden lance', 'Forbidden Lance', 3),
  ('official:fossil dig', 'Fossil Dig', 33),
  ('official:fossil dyna pachycephalo', 'Fossil Dyna Pachycephalo', 100),
  ('official:frightfur patchwork', 'Frightfur Patchwork', 33),
  ('official:fusion destiny', 'Fusion Destiny', 33),
  ('official:gagagaga girl', 'Gagagaga Girl', 15),
  ('official:galaxy photon dragon', 'Galaxy Photon Dragon', 15),
  ('official:gallant granite', 'Gallant Granite', 33),
  ('official:garura, wings of resonant life', 'Garura, Wings of Resonant Life', 4),
  ('official:gateway of the six', 'Gateway of the Six', 100),
  ('official:gem-knight lady lapis lazuli', 'Gem-Knight Lady Lapis Lazuli', 51),
  ('official:gem-knight master diamond', 'Gem-Knight Master Diamond', 66),
  ('official:ghost belle & haunted mansion', 'Ghost Belle & Haunted Mansion', 6),
  ('official:ghost meets girl - a masterful mayakashi shiranui saga', 'Ghost Meets Girl - A Masterful Mayakashi Shiranui Saga', 100),
  ('official:ghost mourner & moonlit chill', 'Ghost Mourner & Moonlit Chill', 5),
  ('official:ghost ogre & snow rabbit', 'Ghost Ogre & Snow Rabbit', 4),
  ('official:ghost sister & spooky dogwood', 'Ghost Sister & Spooky Dogwood', 3),
  ('official:giant trunade', 'Giant Trunade', 40),
  ('official:gigantic spright', 'Gigantic Spright', 15),
  ('official:gimmick puppet nightmare', 'Gimmick Puppet Nightmare', 70),
  ('official:gishki aquamirror', 'Gishki Aquamirror', 1),
  ('official:gishki nekromirror', 'Gishki Nekromirror', 1),
  ('official:give and take', 'Give and Take', 91),
  ('official:gladiator beast tamer editor', 'Gladiator Beast Tamer Editor', 80),
  ('official:glow-up bulb', 'Glow-Up Bulb', 21),
  ('official:goblin biker big gabonga', 'Goblin Biker Big Gabonga', 15),
  ('official:goblin biker grand breakout', 'Goblin Biker Grand Breakout', 7),
  ('official:goblin biker grand entrance', 'Goblin Biker Grand Entrance', 20),
  ('official:gold sarcophagus', 'Gold Sarcophagus', 10),
  ('official:golden cloud beast - malong', 'Golden Cloud Beast - Malong', 4),
  ('official:gozen match', 'Gozen Match', 100),
  ('official:graceful charity', 'Graceful Charity', 40),
  ('official:grapha, dragon lord of dark world', 'Grapha, Dragon Lord of Dark World', 5),
  ('official:grapha, dragon overlord of dark world', 'Grapha, Dragon Overlord of Dark World', 5),
  ('official:grisaille prison', 'Grisaille Prison', 10),
  ('official:guardian chimera', 'Guardian Chimera', 33),
  ('official:guiding quem, the virtuous', 'Guiding Quem, the Virtuous', 3),
  ('official:harpie''s feather duster', 'Harpie''s Feather Duster', 9),
  ('official:harpie''s feather storm', 'Harpie''s Feather Storm', 100),
  ('official:heart of the blue-eyes', 'Heart of the Blue-Eyes', 5),
  ('official:heat wave', 'Heat Wave', 100),
  ('official:heavy storm', 'Heavy Storm', 6),
  ('official:herald of the arc light', 'Herald of the Arc Light', 50),
  ('official:hot red dragon archfiend abyss', 'Hot Red Dragon Archfiend Abyss', 20),
  ('official:hot red dragon archfiend king calamity', 'Hot Red Dragon Archfiend King Calamity', 21),
  ('official:hyper rank-up-magic utopiforce', 'Hyper Rank-Up-Magic Utopiforce', 1),
  ('official:ice ryzeal', 'Ice Ryzeal', 20),
  ('official:ichiki sayori-hime', 'Ichiki Sayori-Hime', 5),
  ('official:ido the supreme magical force', 'Ido the Supreme Magical Force', 100),
  ('official:imperial order', 'Imperial Order', 100),
  ('official:imsety, glory of horus', 'Imsety, Glory of Horus', 33),
  ('official:incredible ecclesia, the virtuous', 'Incredible Ecclesia, the Virtuous', 3),
  ('official:infernal flame banshee', 'Infernal Flame Banshee', 33),
  ('official:infernity launcher', 'Infernity Launcher', 88),
  ('official:infinite impermanence', 'Infinite Impermanence', 12),
  ('official:inspector boarder', 'Inspector Boarder', 20),
  ('official:instant fusion', 'Instant Fusion', 100),
  ('official:interrupted kaiju slumber', 'Interrupted Kaiju Slumber', 10),
  ('official:into the void', 'Into the Void', 7),
  ('official:invoked caliga', 'Invoked Caliga', 100),
  ('official:iron thunder', 'Iron Thunder', 5),
  ('official:jet synchron', 'Jet Synchron', 1),
  ('official:jowgen the spiritualist', 'Jowgen the Spiritualist', 100),
  ('official:junk speeder', 'Junk Speeder', 100),
  ('official:k9-04 noroi', 'K9-04 Noroi', 15),
  ('official:k9-17 "ripper"', 'K9-17 "Ripper"', 30),
  ('official:k9-17 izuna', 'K9-17 Izuna', 20),
  ('official:k9-66a jokul', 'K9-66a Jokul', 33),
  ('official:k9-x "ripper/m"', 'K9-X "Ripper/M"', 10),
  ('official:k9-x "werewolf"', 'K9-X "Werewolf"', 10),
  ('official:k9-�� lupis', 'K9-�� Lupis', 5),
  ('official:kaiser colosseum', 'Kaiser Colosseum', 100),
  ('official:kashtira arise-heart', 'Kashtira Arise-Heart', 97),
  ('official:kashtira fenrir', 'Kashtira Fenrir', 30),
  ('official:kashtira unicorn', 'Kashtira Unicorn', 30),
  ('official:kelbek the ancient vanguard', 'Kelbek the Ancient Vanguard', 50),
  ('official:keldo the sacred protector', 'Keldo the Sacred Protector', 1),
  ('official:ketu dracotail', 'Ketu Dracotail', 15),
  ('official:kewl tune clip', 'Kewl Tune Clip', 6),
  ('official:kewl tune cue', 'Kewl Tune Cue', 6),
  ('official:kewl tune synchro', 'Kewl Tune Synchro', 10),
  ('official:king of the feral imps', 'King of the Feral Imps', 33),
  ('official:king''s sarcophagus', 'King''s Sarcophagus', 33),
  ('official:knight armed dragon, the armored knight dragon', 'Knight Armed Dragon, the Armored Knight Dragon', 3),
  ('official:knightmare corruptor iblee', 'Knightmare Corruptor Iblee', 100),
  ('official:koa''ki meiru drago', 'Koa''ki Meiru Drago', 75),
  ('official:koa''ki meiru guardian', 'Koa''ki Meiru Guardian', 3),
  ('official:koa''ki meiru overload', 'Koa''ki Meiru Overload', 3),
  ('official:koa''ki meiru sandman', 'Koa''ki Meiru Sandman', 3),
  ('official:koa''ki meiru wall', 'Koa''ki Meiru Wall', 3),
  ('official:lady labrynth of the silver castle', 'Lady Labrynth of the Silver Castle', 40),
  ('official:lady''s dragonmaid', 'Lady''s Dragonmaid', 10),
  ('official:laevatein, generaider boss of shadows', 'Laevatein, Generaider Boss of Shadows', 1),
  ('official:last turn', 'Last Turn', 100),
  ('official:last will', 'Last Will', 100),
  ('official:lavalval chain', 'Lavalval Chain', 80),
  ('official:left arm offering', 'Left Arm Offering', 7),
  ('official:legendary fire king ponix', 'Legendary Fire King Ponix', 10),
  ('official:legendary lord six samurai - shi en', 'Legendary Lord Six Samurai - Shi En', 10),
  ('official:legendary six samurai - shi en', 'Legendary Six Samurai - Shi En', 10),
  ('official:level eater', 'Level Eater', 100),
  ('official:life equalizer', 'Life Equalizer', 100),
  ('official:light and darkness dragonlord', 'Light and Darkness Dragonlord', 20),
  ('official:light barrier', 'Light Barrier', 1),
  ('official:light end sublimation dragon', 'Light End Sublimation Dragon', 1),
  ('official:lightning storm', 'Lightning Storm', 12),
  ('official:lightsworn dragonling', 'Lightsworn Dragonling', 10),
  ('official:lonefire blossom', 'Lonefire Blossom', 33),
  ('official:lose 1 turn', 'Lose 1 Turn', 100),
  ('official:lubellion the searing dragon', 'Lubellion the Searing Dragon', 10),
  ('official:lunalight liger dancer', 'Lunalight Liger Dancer', 51),
  ('official:lyrilusc - beryl canary', 'Lyrilusc - Beryl Canary', 5),
  ('official:lyrilusc - bird call', 'Lyrilusc - Bird Call', 20),
  ('official:lyrilusc - independent nightingale', 'Lyrilusc - Independent Nightingale', 1),
  ('official:m-x-saber invoker', 'M-X-Saber Invoker', 33),
  ('official:magical explosion', 'Magical Explosion', 75),
  ('official:magical mid-breaker field', 'Magical Mid-Breaker Field', 60),
  ('official:magical scientist', 'Magical Scientist', 95),
  ('official:magician of black chaos max', 'Magician of Black Chaos MAX', 100),
  ('official:magicians'' souls', 'Magicians'' Souls', 15),
  ('official:majesty''s fiend', 'Majesty''s Fiend', 100),
  ('official:manju of the ten thousand hands', 'Manju of the Ten Thousand Hands', 1),
  ('official:mansion of the dreadful dolls', 'Mansion of the Dreadful Dolls', 100),
  ('official:masked hero dark law', 'Masked HERO Dark Law', 70),
  ('official:masquerade the blazing dragon', 'Masquerade the Blazing Dragon', 16),
  ('official:mass driver', 'Mass Driver', 100),
  ('official:master peace, the true dracoslaying king', 'Master Peace, the True Dracoslaying King', 33),
  ('official:mathmech circular', 'Mathmech Circular', 15),
  ('official:mathmech sigma', 'Mathmech Sigma', 7),
  ('official:maxx "c"', 'Maxx "C"', 50),
  ('official:medius the pure', 'Medius the Pure', 5),
  ('official:megalith anastasis', 'Megalith Anastasis', 33),
  ('official:mementomictlan tecuhtlica - creation king', 'Mementomictlan Tecuhtlica - Creation King', 33),
  ('official:mementotlan bone party', 'Mementotlan Bone Party', 33),
  ('official:mementotlan twin dragon', 'Mementotlan Twin Dragon', 33),
  ('official:mercurium the living quicksilver', 'Mercurium the Living Quicksilver', 10),
  ('official:mereologic aggregator', 'Mereologic Aggregator', 4),
  ('official:metamorphosis', 'Metamorphosis', 5),
  ('official:metaverse', 'Metaverse', 3),
  ('official:mikanko shinbu - noble twins', 'Mikanko Shinbu - Noble Twins', 18),
  ('official:mikanko water arabesque', 'Mikanko Water Arabesque', 10),
  ('official:millennium ankh', 'Millennium Ankh', 3),
  ('official:mind drain', 'Mind Drain', 100),
  ('official:mind master', 'Mind Master', 1),
  ('official:mirrorjade the iceblade dragon', 'Mirrorjade the Iceblade Dragon', 10),
  ('official:miscellaneousaurus', 'Miscellaneousaurus', 67),
  ('official:mistake', 'Mistake', 100),
  ('official:mistaken arrest', 'Mistaken Arrest', 10),
  ('official:mitsurugi prayers', 'Mitsurugi Prayers', 51),
  ('official:mitsurugi ritual', 'Mitsurugi Ritual', 51),
  ('official:monster gate', 'Monster Gate', 50),
  ('official:monster reborn', 'Monster Reborn', 4),
  ('official:morphing jar', 'Morphing Jar', 33),
  ('official:morphtronic telefon', 'Morphtronic Telefon', 55),
  ('official:moulinglacia the elemental lord', 'Moulinglacia the Elemental Lord', 100),
  ('official:mudora the sword oracle', 'Mudora the Sword Oracle', 1),
  ('official:mulcharmy fuwalos', 'Mulcharmy Fuwalos', 7),
  ('official:mulcharmy meowls', 'Mulcharmy Meowls', 2),
  ('official:mulcharmy purulia', 'Mulcharmy Purulia', 9),
  ('official:multi-universe', 'Multi-Universe', 3),
  ('official:mystic mine', 'Mystic Mine', 100),
  ('official:n.as.h. knight', 'N.As.H. Knight', 15),
  ('official:nadir servant', 'Nadir Servant', 20),
  ('official:naturia barkion', 'Naturia Barkion', 10),
  ('official:naturia beast', 'Naturia Beast', 50),
  ('official:naturia exterio', 'Naturia Exterio', 100),
  ('official:necrovalley', 'Necrovalley', 40),
  ('official:neptabyss, the atlantean prince', 'Neptabyss, the Atlantean Prince', 33),
  ('official:nerva the power patron of creation', 'Nerva the Power Patron of Creation', 5),
  ('official:nibiru, the primal being', 'Nibiru, the Primal Being', 6),
  ('official:nightmare apprentice', 'Nightmare Apprentice', 20),
  ('official:nightmare throne', 'Nightmare Throne', 25),
  ('official:noh-p.u.n.k. foxy tune', 'Noh-P.U.N.K. Foxy Tune', 7),
  ('official:noh-p.u.n.k. rising scale', 'Noh-P.U.N.K. Rising Scale', 3),
  ('official:number 1: infection buzzking', 'Number 1: Infection Buzzking', 85),
  ('official:number 1: numeron gate ekam', 'Number 1: Numeron Gate Ekam', 10),
  ('official:number 100: numeron dragon', 'Number 100: Numeron Dragon', 21),
  ('official:number 16: shock master', 'Number 16: Shock Master', 100),
  ('official:number 2: numeron gate dve', 'Number 2: Numeron Gate Dve', 10),
  ('official:number 3: cicada king', 'Number 3: Cicada King', 10),
  ('official:number 3: numeron gate trini', 'Number 3: Numeron Gate Trini', 10),
  ('official:number 38: hope harbinger dragon titanic galaxy', 'Number 38: Hope Harbinger Dragon Titanic Galaxy', 20),
  ('official:number 39: utopia double', 'Number 39: Utopia Double', 80),
  ('official:number 4: numeron gate catvari', 'Number 4: Numeron Gate Catvari', 10),
  ('official:number 40: gimmick puppet of strings', 'Number 40: Gimmick Puppet of Strings', 50),
  ('official:number 41: bagooska the terribly tired tapir', 'Number 41: Bagooska the Terribly Tired Tapir', 100),
  ('official:number 43: manipulator of souls', 'Number 43: Manipulator of Souls', 100),
  ('official:number 59: crooked cook', 'Number 59: Crooked Cook', 100),
  ('official:number 60: dugares the timeless', 'Number 60: Dugares the Timeless', 10),
  ('official:number 67: pair-a-dice smasher', 'Number 67: Pair-a-Dice Smasher', 67),
  ('official:number 69: heraldry crest', 'Number 69: Heraldry Crest', 1),
  ('official:number 75: bamboozling gossip shadow', 'Number 75: Bamboozling Gossip Shadow', 70),
  ('official:number 86: heroic champion - rhongomyniad', 'Number 86: Heroic Champion - Rhongomyniad', 68),
  ('official:number 89: diablosis the mind hacker', 'Number 89: Diablosis the Mind Hacker', 85),
  ('official:number 90: galaxy-eyes photon lord', 'Number 90: Galaxy-Eyes Photon Lord', 10),
  ('official:number 95: galaxy-eyes dark matter dragon', 'Number 95: Galaxy-Eyes Dark Matter Dragon', 50),
  ('official:number 97: draglubion', 'Number 97: Draglubion', 80),
  ('official:number 99: utopia dragonar', 'Number 99: Utopia Dragonar', 80),
  ('official:number c1: numeron chaos gate sunya', 'Number C1: Numeron Chaos Gate Sunya', 10),
  ('official:number c40: gimmick puppet of dark strings', 'Number C40: Gimmick Puppet of Dark Strings', 50),
  ('official:number f0: utopic draco future', 'Number F0: Utopic Draco Future', 20),
  ('official:number s0: utopic zexal', 'Number S0: Utopic ZEXAL', 100),
  ('official:numbers eveil', 'Numbers Eveil', 70),
  ('official:numeron calling', 'Numeron Calling', 30),
  ('official:numeron network', 'Numeron Network', 33),
  ('official:obedience schooled', 'Obedience Schooled', 40),
  ('official:ohime the manifested mikanko', 'Ohime the Manifested Mikanko', 33),
  ('official:ojama duo', 'Ojama Duo', 2),
  ('official:ojama trio', 'Ojama Trio', 3),
  ('official:one day of peace', 'One Day of Peace', 11),
  ('official:one for one', 'One for One', 91),
  ('official:onomatopaira', 'Onomatopaira', 33),
  ('official:original sinful spoils - snake-eye', 'Original Sinful Spoils - Snake-Eye', 100),
  ('official:outer entity azathot', 'Outer Entity Azathot', 100),
  ('official:p.u.n.k. jam dragon drive', 'P.U.N.K. JAM Dragon Drive', 15),
  ('official:painful choice', 'Painful Choice', 95),
  ('official:phantom fortress enterblathnir', 'Phantom Fortress Enterblathnir', 13),
  ('official:phantom knights'' rank-up-magic force', 'Phantom Knights'' Rank-Up-Magic Force', 1),
  ('official:phantom of yubel', 'Phantom of Yubel', 76),
  ('official:pilgrim reaper', 'Pilgrim Reaper', 50),
  ('official:planet pathfinder', 'Planet Pathfinder', 3),
  ('official:pot of desires', 'Pot of Desires', 20),
  ('official:pot of extravagance', 'Pot of Extravagance', 10),
  ('official:pot of greed', 'Pot of Greed', 30),
  ('official:pot of prosperity', 'Pot of Prosperity', 40),
  ('official:powersink stone', 'Powersink Stone', 100),
  ('official:pre-preparation of rites', 'Pre-Preparation of Rites', 10),
  ('official:premature burial', 'Premature Burial', 3),
  ('official:preparation of rites', 'Preparation of Rites', 5),
  ('official:pressured planet wraitsoth', 'Pressured Planet Wraitsoth', 33),
  ('official:primathmech alembertian', 'Primathmech Alembertian', 20),
  ('official:primeval planet perlereino', 'Primeval Planet Perlereino', 50),
  ('official:primite lordly lode', 'Primite Lordly Lode', 33),
  ('official:prohibition', 'Prohibition', 100),
  ('official:pseudo space', 'Pseudo Space', 3),
  ('official:psi-blocker', 'Psi-Blocker', 61),
  ('official:psy-framegear delta', 'PSY-Framegear Delta', 7),
  ('official:psy-framegear epsilon', 'PSY-Framegear Epsilon', 7),
  ('official:psy-framegear gamma', 'PSY-Framegear Gamma', 15),
  ('official:psy-framelord omega', 'PSY-Framelord Omega', 100),
  ('official:psychic end punisher', 'Psychic End Punisher', 20),
  ('official:purrely', 'Purrely', 10),
  ('official:purrely sleepy memory', 'Purrely Sleepy Memory', 10),
  ('official:purrelyly', 'Purrelyly', 7),
  ('official:qq enneagon', 'QQ Enneagon', 1),
  ('official:question', 'Question', 11),
  ('official:quick launch', 'Quick Launch', 33),
  ('official:ra''s disciple', 'Ra''s Disciple', 1),
  ('official:radiant typhoon chant', 'Radiant Typhoon Chant', 10),
  ('official:radiant typhoon eldam', 'Radiant Typhoon Eldam', 7),
  ('official:radiant typhoon vision', 'Radiant Typhoon Vision', 10),
  ('official:rahu dracotail', 'Rahu Dracotail', 10),
  ('official:raider''s knight', 'Raider''s Knight', 80),
  ('official:raigeki', 'Raigeki', 4),
  ('official:rank-up-magic - the seventh one', 'Rank-Up-Magic - The Seventh One', 1),
  ('official:rank-up-magic admiration of the thousands', 'Rank-Up-Magic Admiration of the Thousands', 1),
  ('official:rank-up-magic argent chaos force', 'Rank-Up-Magic Argent Chaos Force', 5),
  ('official:rank-up-magic astral force', 'Rank-Up-Magic Astral Force', 1),
  ('official:rank-up-magic barian''s force', 'Rank-Up-Magic Barian''s Force', 1),
  ('official:rank-up-magic cipher ascension', 'Rank-Up-Magic Cipher Ascension', 1),
  ('official:rank-up-magic doom double force', 'Rank-Up-Magic Doom Double Force', 1),
  ('official:rank-up-magic limited barian''s force', 'Rank-Up-Magic Limited Barian''s Force', 1),
  ('official:rank-up-magic magical force', 'Rank-Up-Magic Magical Force', 1),
  ('official:rank-up-magic numeron force', 'Rank-Up-Magic Numeron Force', 1),
  ('official:rank-up-magic quick chaos', 'Rank-Up-Magic Quick Chaos', 1),
  ('official:rank-up-magic raid force', 'Rank-Up-Magic Raid Force', 1),
  ('official:rank-up-magic raptor''s force', 'Rank-Up-Magic Raptor''s Force', 1),
  ('official:rank-up-magic revolution force', 'Rank-Up-Magic Revolution Force', 1),
  ('official:rank-up-magic skip force', 'Rank-Up-Magic Skip Force', 5),
  ('official:rank-up-magic soul shave force', 'Rank-Up-Magic Soul Shave Force', 5),
  ('official:rank-up-magic zexal force', 'Rank-Up-Magic Zexal Force', 1),
  ('official:reasoning', 'Reasoning', 50),
  ('official:red reboot', 'Red Reboot', 50),
  ('official:red-eyes black fullmetal dragon', 'Red-Eyes Black Fullmetal Dragon', 33),
  ('official:red-eyes dark dragoon', 'Red-Eyes Dark Dragoon', 100),
  ('official:red-eyes flare metal dragon', 'Red-Eyes Flare Metal Dragon', 1),
  ('official:redox, dragon ruler of boulders', 'Redox, Dragon Ruler of Boulders', 5),
  ('official:regenesis', 'Regenesis', 10),
  ('official:regenesis archfiend', 'Regenesis Archfiend', 10),
  ('official:regenesis code', 'Regenesis Code', 10),
  ('official:regenesis sage', 'Regenesis Sage', 7),
  ('official:regenesis warrior', 'Regenesis Warrior', 3),
  ('official:reinforcement of the army', 'Reinforcement of the Army', 33),
  ('official:rescue-ace air lifter', 'Rescue-ACE Air Lifter', 5),
  ('official:rescue-ace impulse', 'Rescue-ACE Impulse', 5),
  ('official:rescue-ace preventer', 'Rescue-ACE Preventer', 10),
  ('official:retaliating "c"', 'Retaliating "C"', 5),
  ('official:return from the different dimension', 'Return from the Different Dimension', 40),
  ('official:return of the dragon lords', 'Return of the Dragon Lords', 7),
  ('official:reversal quiz', 'Reversal Quiz', 100),
  ('official:rise rank-up-magic raidraptor''s force', 'Rise Rank-Up-Magic Raidraptor''s Force', 1),
  ('official:ritual beast tamer elder', 'Ritual Beast Tamer Elder', 10),
  ('official:rivalry of warlords', 'Rivalry of Warlords', 100),
  ('official:ronintoadin', 'Ronintoadin', 60),
  ('official:royal decree', 'Royal Decree', 10),
  ('official:royal magical library', 'Royal Magical Library', 100),
  ('official:royal oppression', 'Royal Oppression', 100),
  ('official:runick tip', 'Runick Tip', 10),
  ('official:ryzeal detonator', 'Ryzeal Detonator', 20),
  ('official:ryzeal duo drive', 'Ryzeal Duo Drive', 20),
  ('official:sales ban', 'Sales Ban', 100),
  ('official:sandwich day', 'Sandwich Day', 3),
  ('official:sangen kaimen', 'Sangen Kaimen', 50),
  ('official:sangen summoning', 'Sangen Summoning', 100),
  ('official:sauravis, the ancient and ascended', 'Sauravis, the Ancient and Ascended', 3),
  ('official:schwarzschild infinity dragon', 'Schwarzschild Infinity Dragon', 33),
  ('official:secret village of the spellcasters', 'Secret Village of the Spellcasters', 100),
  ('official:self-destruct button', 'Self-Destruct Button', 100),
  ('official:sengenjin wakes from a millennium', 'Sengenjin Wakes from a Millennium', 33),
  ('official:senju of the thousand hands', 'Senju of the Thousand Hands', 1),
  ('official:set rotation', 'Set Rotation', 33),
  ('official:shaddoll schism', 'Shaddoll Schism', 10),
  ('official:shien''s smoke signal', 'Shien''s Smoke Signal', 33),
  ('official:shiina, twin tempests of celestial thunder', 'Shiina, Twin Tempests of Celestial Thunder', 10),
  ('official:shooting riser dragon', 'Shooting Riser Dragon', 33),
  ('official:sillva, warlord of dark world', 'Sillva, Warlord of Dark World', 100),
  ('official:silvy of the white forest', 'Silvy of the White Forest', 5),
  ('official:sixth sense', 'Sixth Sense', 65),
  ('official:skill drain', 'Skill Drain', 100),
  ('official:sky striker mobilize - engage!', 'Sky Striker Mobilize - Engage!', 7),
  ('official:smoke grenade of the thief', 'Smoke Grenade of the Thief', 87),
  ('official:snatch steal', 'Snatch Steal', 4),
  ('official:snoww, unlight of dark world', 'Snoww, Unlight of Dark World', 33),
  ('official:solemn judgment', 'Solemn Judgment', 7),
  ('official:solemn scolding', 'Solemn Scolding', 5),
  ('official:solemn strike', 'Solemn Strike', 5),
  ('official:solemn warning', 'Solemn Warning', 5),
  ('official:songs of the dominators', 'Songs of the Dominators', 10),
  ('official:soul charge', 'Soul Charge', 50),
  ('official:soul drain', 'Soul Drain', 100),
  ('official:speedroid terrortop', 'Speedroid Terrortop', 7),
  ('official:spell canceller', 'Spell Canceller', 20),
  ('official:spell card "soul exchange"', 'Spell Card "Soul Exchange"', 3),
  ('official:spenta, the magistus sealer', 'Spenta, the Magistus Sealer', 15),
  ('official:spiritual beast tamer lara', 'Spiritual Beast Tamer Lara', 10),
  ('official:spright starter', 'Spright Starter', 10),
  ('official:stand up centur-ion!', 'Stand Up Centur-Ion!', 5),
  ('official:star seraph scepter', 'Star Seraph Scepter', 5),
  ('official:star seraph sovereignty', 'Star Seraph Sovereignty', 5),
  ('official:stardust sifr divine dragon', 'Stardust Sifr Divine Dragon', 21),
  ('official:starliege seyfert', 'Starliege Seyfert', 33),
  ('official:steel-stringed sacrifice', 'Steel-Stringed Sacrifice', 3),
  ('official:stray purrely street', 'Stray Purrely Street', 5),
  ('official:substitoad', 'Substitoad', 60),
  ('official:subterror guru', 'Subterror Guru', 5),
  ('official:summon limit', 'Summon Limit', 100),
  ('official:super polymerization', 'Super Polymerization', 13),
  ('official:super quantal mech king great magnus', 'Super Quantal Mech King Great Magnus', 33),
  ('official:super starslayer ty-phon - sky crisis', 'Super Starslayer TY-PHON - Sky Crisis', 10),
  ('official:supreme king dragon starving venom', 'Supreme King Dragon Starving Venom', 1),
  ('official:swap frog', 'Swap Frog', 33),
  ('official:sword ryzeal', 'Sword Ryzeal', 20),
  ('official:swordsoul emergence', 'Swordsoul Emergence', 10),
  ('official:swordsoul grandmaster - chixiao', 'Swordsoul Grandmaster - Chixiao', 20),
  ('official:swordsoul strategist longyuan', 'Swordsoul Strategist Longyuan', 5),
  ('official:t.g. hyper librarian', 'T.G. Hyper Librarian', 33),
  ('official:tearlaments havnis', 'Tearlaments Havnis', 50),
  ('official:tearlaments kitkallos', 'Tearlaments Kitkallos', 50),
  ('official:tearlaments merrli', 'Tearlaments Merrli', 50),
  ('official:tearlaments reinoheart', 'Tearlaments Reinoheart', 50),
  ('official:tearlaments scheiren', 'Tearlaments Scheiren', 50),
  ('official:telekinetic charging cell', 'Telekinetic Charging Cell', 100),
  ('official:tellarknight ptolemaeus', 'Tellarknight Ptolemaeus', 100),
  ('official:tempest, dragon ruler of storms', 'Tempest, Dragon Ruler of Storms', 5),
  ('official:tenpai dragon chundra', 'Tenpai Dragon Chundra', 50),
  ('official:tenpai dragon genroku', 'Tenpai Dragon Genroku', 25),
  ('official:tenyi spirit - ashuna', 'Tenyi Spirit - Ashuna', 3),
  ('official:terraforming', 'Terraforming', 33),
  ('official:that grass looks greener', 'That Grass Looks Greener', 50),
  ('official:the black goat laughs', 'The Black Goat Laughs', 10),
  ('official:the bystial lubellion', 'The Bystial Lubellion', 30),
  ('official:the dragon that devours the dogma', 'The Dragon that Devours the Dogma', 5),
  ('official:the fallen & the virtuous', 'The Fallen & The Virtuous', 40),
  ('official:the forceful sentry', 'The Forceful Sentry', 100),
  ('official:the gates of dark world', 'The Gates of Dark World', 5),
  ('official:the gaze of timaeus', 'The Gaze of Timaeus', 1),
  ('official:the last warrior from another planet', 'The Last Warrior from Another Planet', 100),
  ('official:the melody of awakening dragon', 'The Melody of Awakening Dragon', 25),
  ('official:the monarchs erupt', 'The Monarchs Erupt', 50),
  ('official:the phantom knights'' rank-up-magic launch', 'The Phantom Knights'' Rank-Up-Magic Launch', 1),
  ('official:the tyrant neptune', 'The Tyrant Neptune', 100),
  ('official:the unstoppable exodia incarnate', 'The Unstoppable Exodia Incarnate', 20),
  ('official:the zombie vampire', 'The Zombie Vampire', 50),
  ('official:theorealize', 'Theorealize', 5),
  ('official:there can be only one', 'There Can Be Only One', 100),
  ('official:therion "king" regulus', 'Therion "King" Regulus', 20),
  ('official:thunder dragon colossus', 'Thunder Dragon Colossus', 67),
  ('official:thunder king rai-oh', 'Thunder King Rai-Oh', 20),
  ('official:tidal, dragon ruler of waterfalls', 'Tidal, Dragon Ruler of Waterfalls', 5),
  ('official:toadally awesome', 'Toadally Awesome', 20),
  ('official:toon table of contents', 'Toon Table of Contents', 7),
  ('official:totem bird', 'Totem Bird', 10),
  ('official:tour guide from the underworld', 'Tour Guide From the Underworld', 3),
  ('official:trade-in', 'Trade-In', 5),
  ('official:transaction rollback', 'Transaction Rollback', 7),
  ('official:trap dustshoot', 'Trap Dustshoot', 94),
  ('official:trap holic', 'Trap Holic', 7),
  ('official:trap trick', 'Trap Trick', 3),
  ('official:traptrix rafflesia', 'Traptrix Rafflesia', 20),
  ('official:treasures of the kings', 'Treasures of the Kings', 5),
  ('official:tri-brigade mercourier', 'Tri-Brigade Mercourier', 5),
  ('official:triple tactics talent', 'Triple Tactics Talent', 93),
  ('official:triple tactics thrust', 'Triple Tactics Thrust', 13),
  ('official:trishula, dragon of the ice barrier', 'Trishula, Dragon of the Ice Barrier', 13),
  ('official:true king of all calamities', 'True King of All Calamities', 100),
  ('official:tyrant''s tirade', 'Tyrant''s Tirade', 100),
  ('official:ultimate slayer', 'Ultimate Slayer', 1),
  ('official:ultimaya tzolkin', 'Ultimaya Tzolkin', 100),
  ('official:union hangar', 'Union Hangar', 15),
  ('official:upstart goblin', 'Upstart Goblin', 7),
  ('official:uzuhime the manifested mikanko', 'Uzuhime the Manifested Mikanko', 18),
  ('official:vanity''s emptiness', 'Vanity''s Emptiness', 100),
  ('official:vanity''s fiend', 'Vanity''s Fiend', 100),
  ('official:vanity''s ruler', 'Vanity''s Ruler', 100),
  ('official:vanquish soul hollie sue', 'Vanquish Soul Hollie Sue', 33),
  ('official:vanquish soul jiaolong', 'Vanquish Soul Jiaolong', 11),
  ('official:vanquish soul razen', 'Vanquish Soul Razen', 11),
  ('official:varudras, the final bringer of the end times', 'Varudras, the Final Bringer of the End Times', 20),
  ('official:virtual world kyubi - shenshen', 'Virtual World Kyubi - Shenshen', 20),
  ('official:virtual world mai-hime - lulu', 'Virtual World Mai-Hime - Lulu', 3),
  ('official:wandering gryphon rider', 'Wandering Gryphon Rider', 50),
  ('official:wanted: seeker of sinful spoils', 'WANTED: Seeker of Sinful Spoils', 33),
  ('official:welcome labrynth', 'Welcome Labrynth', 20),
  ('official:wind-up carrier zenmaity', 'Wind-Up Carrier Zenmaity', 15),
  ('official:wind-up hunter', 'Wind-Up Hunter', 86),
  ('official:wishes for eyes of blue', 'Wishes for Eyes of Blue', 33),
  ('official:witch of the white forest', 'Witch of the White Forest', 33),
  ('official:world legacy monstrosity', 'World Legacy Monstrosity', 1),
  ('official:zaborg the mega monarch', 'Zaborg the Mega Monarch', 100),
  ('official:zalen the shackled dragon', 'Zalen the Shackled Dragon', 10),
  ('official:zoodiac barrage', 'Zoodiac Barrage', 33),
  ('official:zoodiac broadbull', 'Zoodiac Broadbull', 66),
  ('official:zoodiac drident', 'Zoodiac Drident', 20),
  ('official:zoodiac ratpier', 'Zoodiac Ratpier', 50)
ON CONFLICT (card_id) DO UPDATE
SET card_name = EXCLUDED.card_name,
    points = EXCLUDED.points,
    updated_at = now();
