/**
 * DuelVerse - Cliente Supabase
 * Desenvolvido por Vinícius
 * 
 * Configuração do cliente Supabase para autenticação,
 * banco de dados e tempo real.
 */
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env?.VITE_SUPABASE_URL || 'https://kyhbipferhspuqnyepll.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_H_viYQZPjZezO_TJUmOFqg_gBIXtAVY';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);