/**
 * DuelVerse - Cliente Supabase
 * Desenvolvido por Vinícius
 * 
 * Configuração do cliente Supabase para autenticação,
 * banco de dados e tempo real.
 */
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://kyhbipferhspuqnyepll.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5aGJpcGZlcmhzcHVxbnllcGxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDkxMTEsImV4cCI6MjA2NzA4NTExMX0.dKE3Q6QTWW_ePRidXJXcQ4WqR0kTun7wql6AsTUb_cs';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});